apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  # TODO: Challenge + Extension
  # convert the configmap into secrets and
  # update the deployment to consume those secrets
type: Opaque
data:
    POSTGRES_DB: cG9zdGdyZXM=
    POSTGRES_USER: YWRtaW4=
    POSTGRES_PASSWORD: c3NzMTIz

  

